import{useMemo,useState}from'react';import{FileText,Upload,Search,GitCompare,ScanText,Download,Copy,Check,Sparkles,ChevronRight,Plus,X,Clock3,ShieldCheck}from'lucide-react';
type Doc={name:string;pages:number;size:string;status:string};
const docs:Doc[]=[{name:'Q3 Product Strategy.pdf',pages:18,size:'2.4 MB',status:'Indexed'},{name:'Customer Research 2026.pdf',pages:34,size:'5.8 MB',status:'Indexed'},{name:'Launch Brief.pdf',pages:9,size:'1.1 MB',status:'Ready'}];
const demo={title:'Q3 Product Strategy',summary:'The document proposes a narrower Q3 launch centered on activation, onboarding improvements, and a collaboration flow before the September customer event.',insights:['Activation is the primary growth objective for the quarter.','Onboarding friction is identified as the largest near-term experience issue.','Advanced reporting is intentionally deferred to protect launch scope.'],entities:['Q3 launch','Activation','Onboarding','Collaboration flow'],risks:['Engineering capacity may constrain the beta window.','Customer research could expand the onboarding scope.']};
export default function App(){const[tab,setTab]=useState<'ask'|'compare'|'extract'>('ask'),[question,setQuestion]=useState('What are the main decisions and risks in this document?'),[answer,setAnswer]=useState(demo.summary),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[query,setQuery]=useState('');
const run=()=>{setBusy(true);setTimeout(()=>{const q=question.toLowerCase();setAnswer(q.includes('risk')?'The main risks are constrained engineering capacity during the beta window and the possibility that customer research expands onboarding work.':q.includes('decision')?'The major decisions are to prioritize activation and collaboration for Q3, simplify onboarding, and defer advanced reporting.':demo.summary);setBusy(false)},650)};
const copy=async()=>{await navigator.clipboard?.writeText(answer);setCopied(true);setTimeout(()=>setCopied(false),1200)};
const exportBrief=()=>{const b=new Blob([[demo.title,demo.summary,'',...demo.insights.map(x=>'• '+x),'','RISKS',...demo.risks.map(x=>'• '+x)].join('\n')],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='document-intelligence-brief.txt';a.click()};
const filtered=docs.filter(d=>d.name.toLowerCase().includes(query.toLowerCase()));const confidence=92;
return <div className="app"><header className="top"><div className="brand"><div className="sig">PDF</div><div><b>DOCUMENA</b><small>AI PDF INTELLIGENCE</small></div></div><div className="private"><ShieldCheck size={14}/> LOCAL-FIRST WORKSPACE</div><div className="topActions"><button onClick={exportBrief}><Download size={15}/> Export</button><button className="new"><Plus size={15}/> Add document</button></div></header>
<div className="shell"><aside className="sidebar"><div className="sideTitle">DOCUMENTS <span>{docs.length}</span></div><div className="search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter library"/></div>{filtered.map(d=><button className="doc" key={d.name}><div className="pdficon"><FileText size={18}/></div><div><b>{d.name}</b><small>{d.pages} pages · {d.size}</small></div><span>{d.status}</span></button>)}<div className="libraryCard"><Sparkles size={16}/><b>Document intelligence</b><p>Ask questions, compare files, or extract structured facts without leaving the workspace.</p></div><div className="stats"><span>INDEXED</span><strong>{docs.length}</strong><small>documents ready</small></div></aside>
<main><section className="hero"><div><span className="eyebrow">DOCUMENT OPERATIONS / 02</span><h1>Ask your PDFs<br/><em>better questions.</em></h1><p>Turn long documents into a searchable, review-first intelligence layer for summaries, comparisons, extraction, and Q&amp;A.</p></div><div className="confidence"><span>ANSWER CONFIDENCE</span><strong>{confidence}%</strong><i style={{width:confidence+'%'}}/><small>Grounded in selected document</small></div></section>
<nav className="tabs"><button className={tab==='ask'?'active':''} onClick={()=>setTab('ask')}><Search size={16}/> Ask document</button><button className={tab==='compare'?'active':''} onClick={()=>setTab('compare')}><GitCompare size={16}/> Compare documents</button><button className={tab==='extract'?'active':''} onClick={()=>setTab('extract')}><ScanText size={16}/> Extract facts</button></nav>
<section className="work"><div className="sourcePanel"><div className="panelHead"><div><span>01 / SOURCE</span><h2>Q3 Product Strategy</h2></div><span className="pages">18 pages</span></div><div className="paper"><div className="paperLabel">DOCUMENT PREVIEW</div><h3>Q3 Product Strategy</h3><div className="line l1"/><div className="line l2"/><div className="line l3"/><div className="line l4"/><div className="quote">“Focus the quarter on activation, reduce onboarding friction, and keep the collaboration flow within the Q3 launch.”</div><div className="line l2"/><div className="line l4"/><div className="line l1"/></div><div className="drop"><Upload size={17}/><b>Drop another PDF</b><small>PDF · max 25 MB</small></div></div>
<div className="intelPanel"><div className="panelHead"><div><span>02 / INTELLIGENCE</span><h2>{tab==='ask'?'Ask the document':tab==='compare'?'Document comparison':'Structured extraction'}</h2></div><span className="indexed"><i/> Indexed</span></div>{tab==='ask'?<><label className="question">Question<textarea value={question} onChange={e=>setQuestion(e.target.value)}/></label><button className="ask" onClick={run} disabled={busy}>{busy?'Reading…':<>Ask with context <ChevronRight size={15}/></>}</button><div className="answer"><div className="answerTop"><span><Sparkles size={14}/> GROUNDED ANSWER</span><button onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>}</button></div><p>{answer}</p><div className="citation"><FileText size={13}/><span>Q3 Product Strategy.pdf</span><b>pp. 4–7</b></div></div></>:tab==='compare'?<Compare/>:<Extract/>}</div></section>
<section className="insights"><div className="insightTitle"><span>03 / STRUCTURED BRIEF</span><h2>What matters at a glance.</h2></div><div className="insightGrid"><Card icon={Sparkles} title="Executive summary" text={demo.summary}/><Card icon={Check} title="Key insights" items={demo.insights}/><Card icon={FileText} title="Entities & topics" items={demo.entities}/><Card icon={ShieldCheck} title="Risks / open questions" items={demo.risks}/></div></section></main></div><footer><span><Clock3 size={13}/> Browser-first demonstration · no document leaves this page</span><span>React · TypeScript · Vite</span></footer></div>}
function Card({icon:Icon,title,text,items}:{icon:any;title:string;text?:string;items?:string[]}){return <div className="card"><div className="cardHead"><Icon size={15}/><b>{title}</b></div>{text?<p>{text}</p>:items?.map((x,i)=><div className="bullet" key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></div>)}</div>}
function Compare(){return <div className="compare"><div className="compareHead"><span>DOCUMENT A</span><span>DOCUMENT B</span></div><div className="compareRow"><b>Launch scope</b><p>Collaboration flow included</p><p>Collaboration flow included</p></div><div className="compareRow"><b>Reporting</b><p>Deferred</p><p>Future phase</p></div><div className="compareRow"><b>Beta</b><p>Small customer beta</p><p>Expanded pilot</p></div><button className="outline" onClick={()=>alert('Comparison complete')}>Generate comparison brief <ChevronRight size={14}/></button></div>}
function Extract(){return <div className="extract"><div className="extractItem"><b>Decision</b><span>Collaboration flow remains in Q3.</span></div><div className="extractItem"><b>Owner</b><span>Product + Engineering</span></div><div className="extractItem"><b>Deadline</b><span>September customer event</span></div><div className="extractItem"><b>Priority</b><span>Activation</span></div><button className="outline">Copy JSON-style facts</button></div>}